import { confirm, isCancel, log, note, spinner, text } from '@clack/prompts';
import { Command } from 'commander';
import { spawn } from 'node:child_process';
import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { setConfigValue } from '@agentbox/config';
import { hostOpenCommand } from '@agentbox/sandbox-core';
import { randomBytes } from 'node:crypto';
import { runGitHubAppManifestFlow } from '../control-plane/github-app-manifest.js';
import { handleLifecycleError } from './_errors.js';

const CP_DIR = join(homedir(), '.agentbox', 'control-plane');
const PEM_PATH = join(CP_DIR, 'github-app.pem');
const ENV_PATH = join(CP_DIR, 'control-plane.env');
const META_PATH = join(CP_DIR, 'control-plane.json');

/** Best-effort: open a URL in the host browser (never throws). */
function openInBrowser(url: string): void {
  try {
    const child = spawn(hostOpenCommand(), [url], { detached: true, stdio: 'ignore' });
    child.unref();
  } catch {
    /* the flow logs the URL to open manually */
  }
}

interface SetupOpts {
  name?: string;
  org?: string;
}

const setupSub = new Command('setup')
  .description(
    'Create the GitHub App the control plane leases push tokens with, and write its deploy config (env + admin token)',
  )
  .option('--name <name>', 'GitHub App name (must be globally unique on GitHub)')
  .option('--org <org>', 'create the App under an organization instead of your user account')
  .action(async (opts: SetupOpts) => {
    try {
      const name =
        opts.name ??
        (await text({
          message: 'GitHub App name (must be unique on GitHub)',
          placeholder: 'agentbox-control-plane',
          defaultValue: 'agentbox-control-plane',
        }));
      if (isCancel(name)) {
        log.info('Aborted.');
        return;
      }

      note(
        'Your browser will open to GitHub to create the App. Review the\n' +
          'permissions (Contents + Pull requests: write) and click "Create".',
        'GitHub App',
      );

      const s = spinner();
      s.start('waiting for the GitHub App to be created in your browser');
      const app = await runGitHubAppManifestFlow({
        appName: String(name),
        org: opts.org,
        // Honor GHES overrides (and make the flow scriptable in tests).
        githubUrl: process.env.GITHUB_URL,
        apiBaseUrl: process.env.GITHUB_API_URL,
        openBrowser: openInBrowser,
        log: (line) => s.message(line),
      });
      s.stop(`GitHub App created: ${app.slug} (id ${app.appId})`);

      // Persist the App key + a generated admin token as the plane's deploy env.
      const adminToken = randomBytes(32).toString('hex');
      await mkdir(CP_DIR, { recursive: true });
      await writeFile(PEM_PATH, app.pem, { mode: 0o600 });
      await chmod(PEM_PATH, 0o600);
      const pemB64 = Buffer.from(app.pem, 'utf8').toString('base64');
      const envBody =
        `# AgentBox control plane deploy env (generated by 'agentbox control-plane setup').\n` +
        `# Feed to docker compose (--env-file) or 'vercel env add'. Keep secret.\n` +
        `GITHUB_APP_ID=${app.appId}\n` +
        `GITHUB_APP_PRIVATE_KEY=${pemB64}\n` +
        `AGENTBOX_RELAY_ADMIN_TOKEN=${adminToken}\n`;
      await writeFile(ENV_PATH, envBody, { mode: 0o600 });
      await chmod(ENV_PATH, 0o600);
      await writeFile(
        META_PATH,
        JSON.stringify({ appId: app.appId, slug: app.slug, htmlUrl: app.htmlUrl, installUrl: app.installUrl }, null, 2) + '\n',
        { mode: 0o600 },
      );

      log.success(
        [
          `GitHub App ready. Deploy config written to ${ENV_PATH} (0600).`,
          '',
          'Next steps:',
          `  1. Install the App on your repos: ${app.installUrl}`,
          `  2. Deploy the control plane with that env:`,
          `       Self-host:  cd apps/control-plane && docker compose --env-file ${ENV_PATH} up --build`,
          `       Vercel:     set GITHUB_APP_ID / GITHUB_APP_PRIVATE_KEY / AGENTBOX_RELAY_ADMIN_TOKEN`,
          `                   (+ POSTGRES_URL) via 'vercel env add', then 'vercel deploy --prod'`,
          `  3. Point boxes at it:  agentbox control-plane set-url https://<your-plane-url>`,
        ].join('\n'),
      );

      const openInstall = await confirm({ message: 'Open the App install page now?', initialValue: true });
      if (!isCancel(openInstall) && openInstall) openInBrowser(app.installUrl);
    } catch (err) {
      handleLifecycleError(err);
    }
  });

const setUrlSub = new Command('set-url')
  .description('Point boxes + the CLI at a deployed control plane (sets relay.controlBoxUrl)')
  .argument('<url>', 'base URL of the deployed control plane, e.g. https://plane.example.com')
  .action(async (url: string) => {
    try {
      const trimmed = url.replace(/\/$/, '');
      await setConfigValue('global', 'relay.controlBoxUrl', trimmed, process.cwd());
      log.success(`Set relay.controlBoxUrl = ${trimmed}`);
    } catch (err) {
      handleLifecycleError(err);
    }
  });

interface StatusOpts {
  url?: string;
  json?: boolean;
}

const statusSub = new Command('status')
  .description('Check whether the configured control plane is reachable')
  .option('--url <url>', 'override the control-plane URL (default: relay.controlBoxUrl)')
  .option('--json', 'emit JSON')
  .action(async (opts: StatusOpts) => {
    try {
      const { loadEffectiveConfig } = await import('@agentbox/config');
      const cfg = await loadEffectiveConfig(process.cwd());
      const url = (opts.url ?? cfg.effective.relay.controlBoxUrl ?? '').replace(/\/$/, '');
      if (!url) {
        log.error('No control plane configured. Run `agentbox control-plane set-url <url>` (or pass --url).');
        process.exitCode = 1;
        return;
      }
      let healthy = false;
      let detail = '';
      try {
        const res = await fetch(`${url}/healthz`, { signal: AbortSignal.timeout(8000) });
        healthy = res.ok;
        const body = (await res.json().catch(() => ({}))) as { boxes?: number; events?: number };
        detail = `${String(body.boxes ?? 0)} box(es), ${String(body.events ?? 0)} event(s)`;
      } catch (e) {
        detail = e instanceof Error ? e.name : String(e);
      }
      if (opts.json) {
        process.stdout.write(JSON.stringify({ url, healthy, detail }) + '\n');
        return;
      }
      process.stdout.write(
        [`control plane: ${healthy ? 'reachable' : 'UNREACHABLE'}`, `  url:    ${url}`, `  health: ${detail}`].join('\n') +
          '\n',
      );
    } catch (err) {
      handleLifecycleError(err);
    }
  });

export const controlPlaneCommand = new Command('control-plane')
  .description('Set up + manage the hosted control plane (GitHub App, deploy config, reachability)')
  .addCommand(statusSub, { isDefault: true })
  .addCommand(setupSub)
  .addCommand(setUrlSub);
